apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 hostNetwork: true
 containers:
   - name: myshell
     image: "ubuntu:14.04"
     command:
       - /bin/sleep
       - "10000"
     securityContext:
       capabilities:
         add:
           - NET_ADMIN
